### ISSUE TITLE
question on dmrg_eig

### ISSUE THREAD

**Issue by rkuoyemnbeek** [oseledets/TT-Toolbox#49]
Hi,

Your paper https://www.sciencedirect.com/science/article/pii/S0010465513004293 is of great interest for me. I am writing a paper myself on a related topic. 

I was trying to understand the code. The only lines where I struggled, were the lines related to calculating X_{\neq p}^T A X_{\neq p} . I was wondering what the the idea is behind leftreduce-matrix, rightreduce-matrix and assemble_local_matrix. 

Can you explain the idea or can you point me to a reference where I can find more details about it?

kind regards, 
Koen

**Comment by dolgov** [comment]
Hi Koen,

you may read https://epubs.siam.org/doi/10.1137/100818893 for the fullest background on ALS/DMRG.
X_{\neq i} corresponds to the retraction matrix P_{i,1} there, but this is a theoretical object since it's of size n^d x nr^2. In practice we need to compute directly with the small local matrix A_i = P_{i,1}^T A P_{i,1}. It can be assembled from rolling partial products of P_{i,1}^T, A and P_{i,1}, called G_i and H_{i,1} in Sec. 5.1. These are the tensors computed by leftreduce-matrix and rightreduce-matrix.
Finally, assemble_local_matrix assembles the entire local matrix A_i if we want to compute all its eigenvalues directly. Alternatively, we can compute a fast matrix-vector product within LOBPCG or Jacobi-Davidson as shown in Eqn. (5.2)-(5.3).

Best,
Sergey.

**Comment by rkuoyemnbeek** [comment]
Thank you very much for the answer. It was exactly where I was looking for.
