### ISSUE TITLE
When using cell array, what should the input format be?

### ISSUE THREAD

**Issue by honglizhaobob** [oseledets/TT-Toolbox#58]
Hi,

I read in the documentation of `tt_tensor` that one can input a cell array (non-canonical) in order to construct a TT. I assumed each cell would contain the individual cores, with each core in 3d MATLAB array format (namely `r_k-1` by `n_k` by `r_k`. But it turned out to not work, what should the cell array's format be?

Thanks!

**Comment by dolgov** [comment]
The standard tt_tensor constructor is a legacy of the canonical decomposition, and so it takes a cell array where each cell is a n_k x r_{k-1} x r_k tensor. Moreover, it is limited to trailing ranks 1.
An alternative constructor is provided by a static function cell2core(tt_tensor, Cell), where each Cell{k} is a r_{k-1} x n_k x r_k tensor as you need.

**Comment by honglizhaobob** [comment]
Thanks. I'm still getting an error in my testing (to reconstruct a TT using the cell array), am I still doing something wrong here?

`test_tt = tt_rand(100, 3, 15);

core1 = test_tt{1}; core2 = test_tt{2}; core3 = test_tt{3};
% permute to (n_k x r_{k-1} x r_k)
core1 = permute(core1, [2 1 3]);
core2 = permute(core2, [2 1 3]);
core3 = permute(core3, [2 1 3]);
% create cell array
cell_arr = {core1; core2; core3};

% test tt_tensor constructor
test_tt2 = tt_tensor(cell_arr);
`

Which gives the error:
`
Unable to perform assignment because the left and right sides have a different number of
elements.

Error in tt_tensor (line 96)
       t.core(ps(1):ps(2)-1)=tt{1}(:);
`

**Comment by honglizhaobob** [comment]
Furthermore, for the other constructor, although I have added `@tt_tensor` to my file path, I still get an error as follows if I try to use `cell2core`:

```
tt_tensor.cell2core(tt_tensor(), {randn(1, 100, 20); randn(20, 100, 1)});
```

```
Unable to resolve the name tt_tensor.cell2core.
```

**Comment by dolgov** [comment]
In the tt_tensor constructor example, the first core must have sizes n_1 x r_1, and the last core must have sizes n_d x r_d.  So instead of "core1 = permute(core1, [2 1 3]);" you need to reshape core1 = reshape(core1, size(core1,2), size(core1,3));

Matlab's OOP is peculiar. Firstly, you shouldn't add the @tt_tensor directory itself, just a parent directory of it. This is done correctly by a setup.m script in the root TT-Toolbox directory. Secondly, when methods are listed in separate files in a @-directory, the call tt_tensor.cell2core is invalid, but instead cell2core(tt_tensor, {randn(1, 100, 20); randn(20, 100, 1)}) works. Here tt_tensor is not a method, but a dummy 0-dimensional tt_tensor object that simply selects the correct cell2core implementation. Compare with cell2core(tt_matrix, {randn(1, 10, 100, 20); randn(20, 10, 100, 1)})

**Comment by honglizhaobob** [comment]
Thanks a lot! This is extremely helpful.
