### ISSUE TITLE
Issue from TT to full format

### ISSUE THREAD

**Issue by nicolacavallini** [oseledets/TT-Toolbox#65]
Dears, 

I found an issue in going from TT to full format using TT toolbox.

The resulting and expected matrices do not match.

![issue](https://github.com/oseledets/TT-Toolbox/assets/5601872/848c1c6b-4e53-4178-bdf8-c8215d0f861d)

[Here](https://github.com/nicolacavallini/tt-toolbox-issue/tree/main) a minimal example code to reconstruct the issue.

Am I getting something wrong?

thanks a lot,
best,
Nicola

**Comment by dolgov** [comment]
Dear Nicola,

just compute `expected = kron(b,a);`

This is an old embarrassing inconsistency between the linear algebra definition of the Kronecker product and the order of array elements in Fortran and derived languages like Matlab. In mathematics, the Kronecker $c = a \otimes b := [a_{i} b]$ and matrix $C = a b^T$ products of vectors contain the same elements $a_i b_j$. However, the elements of $c$ are indexed as $c_{(i-1)n+j}$ whereas the elements of $C$ are indexed as $c_{i+(j-1)n}$. The TT-Toolbox implements the latter, since its original purpose was to compress and restore high-dimensional arrays which Matlab stores always in the $i+(j-1)n+...$ order of elements. It is recommended to use `tkron` to compute a Kronecker-like product $a \bar\otimes b := [a b_{i}]$ between tt_tensors and $A \bar\otimes B := [A B_{i,j}]$ between tt_matrices, which match the ordering of the full array.

Best,
Sergey.
